name: 'CloudFormation Delete Action'
description: 'Deletes CloudFormation Stacks'
author: 'Nick Willan'
inputs:
  awsRegion:
    required: true
    description: 'AWS Region'
  stackName:
    required: true
    description: 'CloudFormation Stack Name'
runs:
  using: 'node16'
  main: 'dist/index.js'
